@tool
extends Area3D

var scene: PackedScene = preload("res://Entities/Hazard/MoltenGlassCube/MoltenGlassCube.tscn")

func _ready():
	replace.call_deferred()

func replace():
	# Move all the geometry generated for this node into a replacement coming
	# from the scene.
	var replacement_node: Node3D = scene.instantiate()
	replacement_node.transform = transform
	
	while (get_child_count() > 0):
		var child: Node = get_child(0)
		remove_child(child)
		replacement_node.add_child(child)
	
	get_parent().add_child(replacement_node)
	queue_free()
	
	# Replace the mesh generated by func_godot with a more "blobby" cube.
	var replacement_mesh: MeshInstance3D = replacement_node.get_node("%ReplacementMesh")
	for child in replacement_node.get_children():
		if child != replacement_mesh && child is MeshInstance3D:
			var aabb: AABB = child.get_aabb()
			replacement_mesh.position = aabb.get_center()
			replacement_mesh.scale = aabb.size
			child.visible = false
